name: Publish Docker Image

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker Image for GHCR
        run: |
          # Convert the repository name to lowercase
          REPO_NAME_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/$REPO_NAME_LOWER/my-image:latest
          docker tag my-image:latest $IMAGE_NAME

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/my-image:latest
